# Generated by Django 6.0.1 on 2026-01-12 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('rating_mva', models.FloatField()),
                ('voltage', models.CharField(max_length=50)),
                ('age_years', models.IntegerField()),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Healthy', max_length=20)),
                ('health_score', models.IntegerField(default=100)),
                ('scenario', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transformer_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_oil_temp_c', models.FloatField(blank=True, null=True)),
                ('winding_temp_c', models.FloatField(blank=True, null=True)),
                ('ambient_temp_c', models.FloatField(blank=True, null=True)),
                ('load_percent', models.FloatField(blank=True, null=True)),
                ('moisture_ppm', models.FloatField(blank=True, null=True)),
                ('tan_delta_percent', models.FloatField(blank=True, null=True)),
                ('breakdown_voltage_kv', models.FloatField(blank=True, null=True)),
                ('h2_ppm', models.FloatField(blank=True, null=True)),
                ('ch4_ppm', models.FloatField(blank=True, null=True)),
                ('c2h2_ppm', models.FloatField(blank=True, null=True)),
                ('c2h4_ppm', models.FloatField(blank=True, null=True)),
                ('c2h6_ppm', models.FloatField(blank=True, null=True)),
                ('co_ppm', models.FloatField(blank=True, null=True)),
                ('co2_ppm', models.FloatField(blank=True, null=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.transformer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('severity', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='monitoring.transformer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monitoring.transformer')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='monitoring.transformer')),
            ],
        ),
    ]
